### ISSUE TITLE
Error while installing the application from github

### ISSUE THREAD

**Issue by isasmendiagus** [scanoss/audit-workbench#574]
## Steps to reproduce:

1. Clone the repository in a fresh Linux installation
2. Run npm install 

## Log reported:

```
> scanoss-workbench@1.5.0 link-modules
> node -r ts-node/register ../../.erb/scripts/link-modules.ts

Error: EEXIST: file already exists, symlink '/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/release/app/node_modules' -> '/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/src/node_modules'
    at Object.symlinkSync (node:fs:1700:3)
    at Object.<anonymous> (/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/.erb/scripts/link-modules.ts:8:6)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module.m._compile (/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.require.extensions.<computed> [as .ts] (/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -17,
  syscall: 'symlink',
  code: 'EEXIST',
  path: '/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/release/app/node_modules',
  dest: '/media/ubuntu/1a2ed4f8-4e1d-4ed1-801e-40304d686053/Projects/SCANOSS/audit-workbench/src/node_modules'
}
```

**Comment by isasmendiagus** [comment]
SOLUTION:  Remove the existing symlink located at `src/node_modules` then re-run `npm install`
